export const GAS_APP_IDEAS = [
  { name: "Inventory Management", desc: "Manajemen stok barang dengan barcode & laporan", sheets: ["Products", "StockIn", "StockOut", "Suppliers"] },
  { name: "Simple CRM", desc: "Customer Relationship Management untuk UMKM", sheets: ["Leads", "Contacts", "Deals", "Activities"] },
  { name: "Employee Attendance", desc: "Sistem absensi karyawan dengan GPS & foto", sheets: ["Employees", "Attendance", "LeaveRequests"] },
  { name: "Expense Tracker", desc: "Pelacakan pengeluaran tim dengan approval", sheets: ["Expenses", "Categories", "Approvals", "Users"] },
  { name: "Project Management Lite", desc: "Manajemen proyek sederhana dengan task & deadline", sheets: ["Projects", "Tasks", "TeamMembers", "Comments"] },
  { name: "Invoice Generator", desc: "Pembuatan invoice otomatis + tracking pembayaran", sheets: ["Invoices", "Clients", "Items", "Payments"] },
  { name: "Helpdesk Ticket System", desc: "Sistem tiket customer service", sheets: ["Tickets", "Customers", "Agents", "Responses"] },
  { name: "Event Registration", desc: "Pendaftaran event + QR code check-in", sheets: ["Events", "Registrations", "Attendees", "Checkins"] },
  { name: "Asset Management", desc: "Manajemen aset perusahaan (laptop, kendaraan, dll)", sheets: ["Assets", "Categories", "Assignments", "Maintenance"] },
  { name: "Simple HRIS", desc: "Human Resource Information System", sheets: ["Employees", "Departments", "Positions", "Payroll"] },
  { name: "Content Calendar", desc: "Kalender konten media sosial tim", sheets: ["Content", "Platforms", "Team", "Analytics"] },
  { name: "Vendor Management", desc: "Manajemen vendor & kontrak", sheets: ["Vendors", "Contracts", "Evaluations", "Documents"] },
  { name: "Meeting Room Booking", desc: "Sistem booking ruang meeting", sheets: ["Rooms", "Bookings", "Users", "Equipment"] },
  { name: "Customer Feedback", desc: "Pengumpulan & analisis feedback pelanggan", sheets: ["Feedback", "Surveys", "Responses", "Reports"] },
  { name: "Simple POS System", desc: "Point of Sale untuk toko kecil", sheets: ["Products", "Sales", "Customers", "Cashier"] },
  { name: "Document Approval Workflow", desc: "Workflow approval dokumen internal", sheets: ["Documents", "Approvals", "Users", "History"] },
  { name: "Training Management", desc: "Manajemen pelatihan karyawan", sheets: ["Trainings", "Participants", "Materials", "Certificates"] },
  { name: "Simple Accounting", desc: "Pembukuan sederhana (kas, bank, jurnal)", sheets: ["Transactions", "Accounts", "Categories", "Reports"] },
  { name: "Task Assignment Board", desc: "Papan tugas tim seperti Trello mini", sheets: ["Boards", "Tasks", "Members", "Comments"] },
  { name: "Visitor Management", desc: "Sistem manajemen tamu kantor", sheets: ["Visitors", "Hosts", "Checkins", "Badges"] },
  { name: "Knowledge Base", desc: "Basis pengetahuan internal perusahaan", sheets: ["Articles", "Categories", "Tags", "Authors"] },
  { name: "Simple E-commerce Backend", desc: "Backend untuk toko online sederhana", sheets: ["Products", "Orders", "Customers", "Inventory"] },
  { name: "Performance Review", desc: "Sistem penilaian kinerja karyawan", sheets: ["Reviews", "Employees", "Criteria", "Goals"] },
  { name: "Bug Tracking", desc: "Pelacakan bug & issue development", sheets: ["Issues", "Projects", "Assignees", "Comments"] },
  { name: "Resource Booking", desc: "Booking peralatan & resource kantor", sheets: ["Resources", "Bookings", "Users", "Categories"] },
  { name: "Simple Blog CMS", desc: "Content Management System untuk blog", sheets: ["Posts", "Categories", "Authors", "Comments"] },
  { name: "Lead Generation Form", desc: "Form capture lead + auto follow-up", sheets: ["Leads", "Sources", "Followups", "Status"] },
  { name: "IT Asset Request", desc: "Permintaan & approval aset IT", sheets: ["Requests", "Assets", "Users", "Approvals"] },
  { name: "Simple Membership System", desc: "Manajemen keanggotaan komunitas", sheets: ["Members", "Plans", "Payments", "Renewals"] },
  { name: "Daily Sales Report", desc: "Laporan penjualan harian otomatis", sheets: ["Sales", "Products", "Staff", "Reports"] },
  { name: "Complaint Management", desc: "Manajemen keluhan pelanggan", sheets: ["Complaints", "Customers", "Resolutions", "SLA"] },
  { name: "Simple Wiki", desc: "Wiki internal untuk dokumentasi tim", sheets: ["Pages", "Categories", "Revisions", "Authors"] },
  { name: "Vehicle Fleet Management", desc: "Manajemen armada kendaraan", sheets: ["Vehicles", "Drivers", "Trips", "Maintenance"] },
  { name: "Simple Survey Tool", desc: "Pembuatan & distribusi survei", sheets: ["Surveys", "Questions", "Responses", "Reports"] },
  { name: "Onboarding Checklist", desc: "Checklist onboarding karyawan baru", sheets: ["Employees", "Checklists", "Tasks", "Progress"] },
  { name: "Simple Donation Tracker", desc: "Pelacakan donasi & donor", sheets: ["Donors", "Donations", "Campaigns", "Reports"] },
  { name: "Equipment Maintenance Log", desc: "Catatan perawatan peralatan", sheets: ["Equipment", "Maintenance", "Technicians", "History"] },
  { name: "Simple Newsletter Manager", desc: "Manajemen subscriber newsletter", sheets: ["Subscribers", "Campaigns", "Opens", "Clicks"] },
  { name: "Task Time Tracker", desc: "Pelacakan waktu pengerjaan tugas", sheets: ["Tasks", "TimeLogs", "Users", "Projects"] },
  { name: "Simple Quotation System", desc: "Pembuatan & tracking quotation", sheets: ["Quotations", "Clients", "Items", "Revisions"] },
  { name: "Internal Job Posting", desc: "Lowongan kerja internal perusahaan", sheets: ["Jobs", "Applicants", "Stages", "Notes"] },
  { name: "Simple File Request System", desc: "Permintaan & approval file dokumen", sheets: ["Requests", "Files", "Approvers", "History"] },
  { name: "Event Volunteer Management", desc: "Manajemen relawan event", sheets: ["Events", "Volunteers", "Shifts", "Checkins"] },
  { name: "Simple Audit Log", desc: "Catatan aktivitas sistem", sheets: ["Logs", "Users", "Actions", "Entities"] },
  { name: "Product Catalog Manager", desc: "Manajemen katalog produk digital", sheets: ["Products", "Categories", "Variants", "Media"] },
  { name: "Simple Referral Program", desc: "Program referral & reward", sheets: ["Referrers", "Referrals", "Rewards", "Payouts"] },
  { name: "Training Attendance", desc: "Absensi pelatihan karyawan", sheets: ["Trainings", "Participants", "Attendance", "Certificates"] },
  { name: "Simple SLA Tracker", desc: "Pelacakan Service Level Agreement", sheets: ["Tickets", "SLAs", "Escalations", "Reports"] },
  { name: "Internal Marketplace", desc: "Marketplace internal antar divisi", sheets: ["Items", "Sellers", "Buyers", "Transactions"] },
  { name: "Simple Compliance Tracker", desc: "Pelacakan kepatuhan regulasi", sheets: ["Requirements", "Compliance", "Evidence", "Audits"] },
];

export const GAS_PRO_SPECS = [
  { name: "Lead Routing & Follow-up", outcome: "mengumpulkan lead dari form, memberi skor, dan mengatur follow-up otomatis", sheets: ["Leads", "Sources", "FollowUps", "Users", "AuditLog"], requirements: ["lead scoring", "assignment round-robin", "reminder email", "status pipeline"], audience: "tim sales UMKM" },
  { name: "Purchase Request Approval", outcome: "mengelola permintaan pembelian dari pengajuan sampai approval bertingkat", sheets: ["Requests", "Items", "Approvers", "Users", "AuditLog"], requirements: ["approval threshold", "reject dengan alasan", "audit trail", "email notification"], audience: "perusahaan menengah" },
  { name: "Multi-Branch Sales Dashboard", outcome: "menggabungkan laporan penjualan dari banyak cabang ke dashboard manajemen", sheets: ["Branches", "Sales", "Products", "Targets", "Users"], requirements: ["filter cabang", "target vs actual", "date range", "CSV export"], audience: "owner retail" },
  { name: "Service Appointment Booking", outcome: "memungkinkan pelanggan memilih layanan, slot, dan menerima konfirmasi booking", sheets: ["Services", "Slots", "Bookings", "Customers", "Settings"], requirements: ["conflict prevention", "reschedule", "cancel policy", "reminder email"], audience: "salon atau klinik" },
  { name: "Quotation to Invoice Workflow", outcome: "mengubah quotation yang disetujui menjadi invoice dan melacak pembayaran", sheets: ["Quotations", "Invoices", "Clients", "LineItems", "Payments"], requirements: ["numbering atomik", "PDF export", "payment status", "overdue reminder"], audience: "freelancer dan agency" },
  { name: "Marketing Campaign Planner", outcome: "merencanakan campaign lintas channel dengan owner, budget, dan KPI", sheets: ["Campaigns", "Channels", "Tasks", "Budgets", "KPIs"], requirements: ["calendar view", "budget tracking", "approval", "KPI dashboard"], audience: "marketing team" },
  { name: "Customer Onboarding Portal", outcome: "mengumpulkan data onboarding pelanggan dan menampilkan progress checklist", sheets: ["Customers", "Checklists", "Documents", "Owners", "AuditLog"], requirements: ["secure token", "document checklist", "progress percent", "email reminder"], audience: "agency dan konsultan" },
  { name: "Warehouse Pick-Pack-Ship", outcome: "mengelola order gudang dari picking sampai pengiriman", sheets: ["Orders", "OrderItems", "Products", "PickLists", "Shipments"], requirements: ["stock reservation", "barcode-ready UI", "packing status", "shipping log"], audience: "operator gudang" },
  { name: "Subscription Renewal Tracker", outcome: "memantau kontrak berlangganan dan mengirim pengingat renewal", sheets: ["Subscriptions", "Customers", "Plans", "Renewals", "Notifications"], requirements: ["renewal forecast", "grace period", "reminder schedule", "revenue summary"], audience: "bisnis jasa berulang" },
  { name: "Quality Inspection Checklist", outcome: "mencatat inspeksi kualitas dengan bukti foto dan hasil pass/fail", sheets: ["Inspections", "Checklists", "Products", "Inspectors", "Evidence"], requirements: ["required fields", "pass/fail rules", "photo link", "inspection report"], audience: "operasional dan manufaktur ringan" },
  { name: "Customer Loyalty Points", outcome: "menghitung poin pelanggan, tier membership, dan penukaran reward", sheets: ["Customers", "Transactions", "PointRules", "Rewards", "Redemptions"], requirements: ["idempotent transaction", "balance ledger", "expiry", "redemption approval"], audience: "retail dan ecommerce" },
  { name: "Public Complaint Portal", outcome: "menerima keluhan publik dengan nomor tiket dan SLA transparan", sheets: ["Complaints", "Categories", "Assignments", "SLA", "Updates"], requirements: ["public ticket token", "PII minimization", "SLA escalation", "status page"], audience: "organisasi layanan publik" },
  { name: "School Enrollment Intake", outcome: "mengelola pendaftaran siswa, verifikasi berkas, dan status seleksi", sheets: ["Applicants", "Documents", "Programs", "Reviewers", "Decisions"], requirements: ["unique application code", "document checklist", "review rubric", "email status"], audience: "sekolah dan lembaga kursus" },
  { name: "Community Membership Portal", outcome: "mengelola anggota komunitas, iuran, event, dan kehadiran", sheets: ["Members", "Plans", "Payments", "Events", "Attendance"], requirements: ["membership status", "payment reconciliation", "event RSVP", "member search"], audience: "komunitas dan asosiasi" },
  { name: "RMA Return Management", outcome: "mengelola retur produk dari request sampai inspection dan replacement", sheets: ["Returns", "Orders", "Products", "Inspections", "Resolutions"], requirements: ["return reason", "eligibility rules", "status workflow", "resolution report"], audience: "toko online" },
  { name: "Recruitment Interview Pipeline", outcome: "mengatur kandidat, jadwal interview, scorecard, dan keputusan hiring", sheets: ["Candidates", "Jobs", "Interviews", "Scorecards", "Decisions"], requirements: ["interviewer access", "scorecard rubric", "calendar invite", "PII protection"], audience: "HR startup" },
  { name: "Procurement Vendor Scorecard", outcome: "menilai vendor berdasarkan delivery, kualitas, biaya, dan risiko", sheets: ["Vendors", "Purchases", "Deliveries", "Scores", "Contracts"], requirements: ["weighted scoring", "period comparison", "risk flags", "export report"], audience: "procurement team" },
  { name: "Internal IT Help Center", outcome: "menyediakan katalog layanan IT dan tracking tiket internal", sheets: ["Tickets", "Services", "Agents", "KnowledgeBase", "SLA"], requirements: ["service catalog", "auto assignment", "SLA timer", "knowledge suggestions"], audience: "tim IT internal" },
  { name: "Field Visit Report", outcome: "mencatat kunjungan lapangan, lokasi, temuan, dan tindak lanjut", sheets: ["Visits", "Clients", "Findings", "Actions", "Users"], requirements: ["mobile-first form", "timestamp", "map link", "photo evidence"], audience: "sales dan teknisi lapangan" },
  { name: "Donation Campaign Portal", outcome: "menampilkan campaign donasi, transaksi donor, dan laporan transparan", sheets: ["Campaigns", "Donors", "Donations", "Updates", "Reports"], requirements: ["donor receipt", "campaign progress", "anonymous option", "monthly report"], audience: "yayasan dan organisasi sosial" },
  { name: "Digital Product Delivery", outcome: "mengirim link produk digital setelah order diverifikasi", sheets: ["Products", "Orders", "Customers", "Deliveries", "AccessLog"], requirements: ["signed expiring link", "download tracking", "order verification", "resend email"], audience: "creator produk digital" },
  { name: "Freelance Timesheet & Billing", outcome: "mengubah timesheet freelancer menjadi billing dan laporan klien", sheets: ["Projects", "TimeLogs", "Clients", "Rates", "Invoices"], requirements: ["timer/manual log", "approval client", "billable rules", "invoice summary"], audience: "freelancer dan studio" },
  { name: "Restaurant Kitchen Display", outcome: "mengirim order ke antrian dapur berdasarkan status dan prioritas", sheets: ["Orders", "OrderItems", "Menu", "Stations", "Events"], requirements: ["kitchen queue", "priority flags", "prep timer", "daily report"], audience: "restoran kecil" },
  { name: "Property Viewing Scheduler", outcome: "mengatur permintaan kunjungan properti dan follow-up agen", sheets: ["Properties", "Leads", "Viewings", "Agents", "FollowUps"], requirements: ["slot locking", "agent assignment", "reminder", "lead conversion"], audience: "agen properti" },
  { name: "Insurance Claim Intake", outcome: "mengumpulkan klaim, bukti, pemeriksaan, dan keputusan", sheets: ["Claims", "Policies", "Customers", "Evidence", "Decisions"], requirements: ["claim number", "document validation", "review queue", "decision audit"], audience: "broker dan administrator" },
  { name: "Social Content Approval", outcome: "mengatur draft konten dari writer sampai approval publisher", sheets: ["Content", "Platforms", "Reviewers", "Calendar", "Revisions"], requirements: ["version history", "approval status", "publish schedule", "content checklist"], audience: "social media team" },
  { name: "Grant Application Review", outcome: "mengelola pengajuan grant dengan rubric penilaian dan ranking", sheets: ["Applications", "Applicants", "Criteria", "Reviews", "Decisions"], requirements: ["weighted rubric", "reviewer assignment", "conflict declaration", "ranking report"], audience: "program grant" },
  { name: "Clinic Queue Dashboard", outcome: "menampilkan antrian layanan klinik dengan nomor panggilan", sheets: ["Patients", "Queues", "Services", "Rooms", "Events"], requirements: ["queue number", "status transitions", "TV display", "daily metrics"], audience: "klinik dan layanan appointment" },
  { name: "Construction Daily Log", outcome: "mencatat progres proyek, pekerja, material, dan kendala harian", sheets: ["Projects", "DailyLogs", "Workers", "Materials", "Issues"], requirements: ["mobile input", "weather note", "progress percent", "photo evidence"], audience: "kontraktor dan site manager" },
  { name: "Business KPI Scorecard", outcome: "mengumpulkan KPI dari tim dan menghitung scorecard manajemen", sheets: ["KPIs", "Owners", "Targets", "Actuals", "Reviews"], requirements: ["period lock", "target vs actual", "owner reminder", "executive dashboard"], audience: "manajemen perusahaan" },
];
