export const categoriesSeed = [
  { slug: "marketing", name: "Marketing", icon: "📣", color: "#ec4899", description: "Copywriting, Meta Ads, TikTok Ads, Instagram Ads & lainnya." },
  { slug: "bisnis", name: "Bisnis", icon: "💼", color: "#6366f1", description: "SOP, Proposal, Pitch Deck, Business Plan." },
  { slug: "customer-service", name: "Customer Service", icon: "💬", color: "#14b8a6", description: "Auto reply, complaint handling, follow up, closing." },
  { slug: "coding", name: "Coding", icon: "💻", color: "#0ea5e9", description: "React, Next.js, Laravel, Node.js, Python, Flutter." },
  { slug: "ui-ux", name: "UI/UX", icon: "🎨", color: "#f59e0b", description: "Landing page, dashboard, mobile app design." },
  { slug: "desain", name: "Desain", icon: "🖼️", color: "#a855f7", description: "Canva, Photoshop, Midjourney, image prompt." },
  { slug: "produktivitas", name: "Produktivitas", icon: "⚡", color: "#22c55e", description: "Email, resume, CV, notulen, meeting." },
  { slug: "pendidikan", name: "Pendidikan", icon: "🎓", color: "#3b82f6", description: "Essay, skripsi, ringkasan, presentasi." },
  { slug: "ai-automation", name: "AI Automation", icon: "🤖", color: "#ef4444", description: "WhatsApp AI, CRM AI, Sales AI, Chatbot AI." },
  { slug: "prompt-engineering", name: "Prompt Engineering", icon: "🧠", color: "#8b5cf6", description: "Chain of Thought, Role Prompt, Few Shot, Multi Agent." },
];

type PromptSeed = {
  slug: string;
  title: string;
  description: string;
  category: string;
  content: string;
  usage: string;
  exampleOutput: string;
  level: string;
  supportedAi: string[];
  tags: string[];
  followUps?: string[];
  isPremium: boolean;
  isTrending?: boolean;
  isBestSeller?: boolean;
  usersCount: number;
  copyCount: number;
};

// Prompt lanjutan universal — bisa dipakai untuk menyempurnakan hasil apa pun.
export const universalFollowUps = [
  "Buat 3 variasi alternatif dari hasil di atas dengan gaya/angle yang berbeda, lalu jelaskan kapan sebaiknya masing-masing dipakai.",
  "Kritik hasil di atas secara jujur: apa kelemahannya, lalu perbaiki menjadi versi yang lebih kuat.",
  "Sesuaikan hasil agar lebih singkat untuk mobile, dan buat juga versi yang lebih detail untuk desktop.",
];

const ai = {
  all: ["ChatGPT", "Claude", "Gemini", "Grok", "DeepSeek"],
  chat: ["ChatGPT", "Claude", "Gemini"],
  code: ["ChatGPT", "Claude", "DeepSeek", "Copilot"],
  image: ["Midjourney", "DALL·E", "Stable Diffusion"],
};

export const promptsSeed: PromptSeed[] = [
  {
    slug: "meta-ads-skincare-konversi-tinggi",
    title: "Meta Ads Skincare Konversi Tinggi",
    description: "Hasilkan copy iklan Meta Ads untuk produk skincare dengan hook, benefit, dan CTA yang kuat.",
    category: "marketing",
    content:
      "Kamu adalah copywriter iklan berpengalaman spesialis Meta Ads. Buatkan 3 variasi copy iklan Facebook/Instagram untuk produk skincare berikut:\n\nProduk: [ISI PRODUK]\nTarget audiens: [ISI TARGET]\nMasalah utama pelanggan: [ISI MASALAH]\nUnique selling point: [ISI USP]\n\nUntuk setiap variasi sertakan: Hook menarik di 3 detik pertama, 2-3 benefit utama, social proof singkat, dan CTA yang mendorong klik. Gunakan bahasa Indonesia yang persuasif namun tidak berlebihan. Tambahkan 5 saran headline dan 3 saran primary text.",
    usage: "Ganti bagian [ISI ...] dengan detail produkmu, lalu jalankan di model AI favoritmu.",
    exampleOutput: "Variasi 1 — Hook: \"Kulit kusam bikin nggak pede? Ini rahasianya...\" ...",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["meta ads", "copywriting", "skincare", "facebook ads"],
    followUps: [
      "Dari 3 variasi di atas, pilih yang paling kuat lalu buat 5 turunan headline A/B test dengan sudut emosi berbeda (takut, ingin, penasaran, sosial, urgensi).",
      "Tulis ulang copy pemenang untuk format Reels/Story 15 detik: bagi menjadi scene per detik lengkap dengan teks overlay dan voice-over.",
      "Buatkan 10 komentar 'social proof' natural (seolah dari pembeli) yang bisa dipin di kolom komentar iklan untuk meningkatkan kepercayaan.",
    ],
    isPremium: false,
    isTrending: true,
    isBestSeller: true,
    usersCount: 4820,
    copyCount: 9130,
  },
  {
    slug: "tiktok-ads-viral-hook",
    title: "TikTok Ads Viral Hook Generator",
    description: "Buat 10 hook video TikTok Ads yang menghentikan scroll dalam 3 detik pertama.",
    category: "marketing",
    content:
      "Bertindaklah sebagai kreator TikTok Ads dengan jutaan views. Buatkan 10 hook video (3 detik pertama) untuk produk [ISI PRODUK] dengan target [ISI TARGET]. Setiap hook harus memancing rasa penasaran, menyentuh pain point, atau memberi janji hasil. Sertakan saran visual singkat dan teks overlay untuk masing-masing hook.",
    usage: "Isi produk dan target, gunakan hasil sebagai naskah opening video.",
    exampleOutput: "1. \"Aku berhenti beli ini setelah tahu faktanya...\" (visual: tangan menaruh produk)",
    level: "Menengah",
    supportedAi: ai.chat,
    tags: ["tiktok ads", "hook", "video", "viral"],
    isPremium: true,
    isTrending: true,
    usersCount: 3210,
    copyCount: 5400,
  },
  {
    slug: "copywriting-aida-produk-digital",
    title: "Copywriting AIDA Produk Digital",
    description: "Struktur AIDA lengkap untuk halaman penjualan produk digital.",
    category: "marketing",
    content:
      "Tuliskan sales copy dengan formula AIDA (Attention, Interest, Desire, Action) untuk produk digital berikut: [ISI PRODUK]. Target: [ISI TARGET]. Sertakan headline utama, subheadline, bullet benefit, penanganan keberatan, garansi, dan CTA. Panjang menengah, tone profesional namun hangat.",
    usage: "Cocok untuk landing page, sales page, dan email penjualan.",
    exampleOutput: "Attention: \"Berhenti membuang waktu untuk...\"",
    level: "Menengah",
    supportedAi: ai.chat,
    tags: ["copywriting", "aida", "sales page", "produk digital"],
    isPremium: false,
    usersCount: 2760,
    copyCount: 4100,
  },
  {
    slug: "sop-operasional-toko-online",
    title: "SOP Operasional Toko Online",
    description: "Buat SOP lengkap operasional harian toko online dari order hingga after sales.",
    category: "bisnis",
    content:
      "Bertindaklah sebagai konsultan operasional. Buatkan SOP (Standard Operating Procedure) lengkap untuk toko online [ISI NAMA BISNIS] yang menjual [ISI PRODUK]. Bagi menjadi tahapan: penerimaan order, konfirmasi pembayaran, packing, pengiriman, penanganan komplain, dan after sales. Tampilkan dalam format bernomor dengan penanggung jawab dan target waktu setiap langkah.",
    usage: "Isi nama bisnis dan produk untuk mendapatkan SOP siap pakai.",
    exampleOutput: "1. Penerimaan Order — PIC: Admin CS — Maks 15 menit ...",
    level: "Menengah",
    supportedAi: ai.chat,
    tags: ["sop", "operasional", "toko online", "umkm"],
    isPremium: true,
    isBestSeller: true,
    usersCount: 1980,
    copyCount: 3020,
  },
  {
    slug: "business-plan-startup",
    title: "Business Plan Startup Lengkap",
    description: "Kerangka business plan investor-ready untuk startup atau UMKM.",
    category: "bisnis",
    content:
      "Susun business plan lengkap untuk ide bisnis berikut: [ISI IDE]. Sertakan ringkasan eksekutif, analisis pasar, target segmen, model bisnis (revenue streams), analisis kompetitor, strategi pemasaran, proyeksi keuangan sederhana 12 bulan, dan kebutuhan modal. Gunakan bahasa yang jelas dan siap dipresentasikan ke investor.",
    usage: "Deskripsikan ide bisnismu selengkap mungkin untuk hasil terbaik.",
    exampleOutput: "Ringkasan Eksekutif: [Nama] adalah platform yang...",
    level: "Lanjutan",
    supportedAi: ai.all,
    tags: ["business plan", "startup", "investor", "strategi"],
    isPremium: true,
    isTrending: true,
    usersCount: 1540,
    copyCount: 2210,
  },
  {
    slug: "cs-handle-komplain-profesional",
    title: "Balasan Komplain Pelanggan Profesional",
    description: "Template respon customer service untuk menangani komplain dengan empati.",
    category: "customer-service",
    content:
      "Kamu adalah customer service profesional. Buat balasan untuk komplain pelanggan berikut: [ISI KOMPLAIN]. Balasan harus: mengakui perasaan pelanggan, meminta maaf bila perlu, menawarkan solusi konkret, dan menjaga hubungan baik. Berikan 2 versi: formal dan santai (WhatsApp).",
    usage: "Tempel isi komplain pelanggan untuk mendapatkan balasan siap kirim.",
    exampleOutput: "Halo Kak, kami mohon maaf atas ketidaknyamanannya...",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["customer service", "komplain", "whatsapp", "template"],
    isPremium: false,
    isBestSeller: true,
    usersCount: 3620,
    copyCount: 6800,
  },
  {
    slug: "follow-up-closing-chat",
    title: "Follow Up & Closing via Chat",
    description: "Rangkaian pesan follow up yang mendorong calon pembeli untuk closing.",
    category: "customer-service",
    content:
      "Buatkan rangkaian 5 pesan follow up (spaced) untuk calon pembeli yang sudah tanya-tanya tapi belum membeli produk [ISI PRODUK]. Setiap pesan singkat, tidak memaksa, memberi nilai tambah, dan diakhiri soft CTA. Gunakan gaya chat WhatsApp yang natural.",
    usage: "Kirim bertahap dari hari ke-1 sampai hari ke-5.",
    exampleOutput: "Hari 1: \"Halo Kak, masih ada yang bisa dibantu soal...\"",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["follow up", "closing", "sales", "whatsapp"],
    isPremium: true,
    usersCount: 2140,
    copyCount: 3900,
  },
  {
    slug: "review-kode-react-nextjs",
    title: "Code Review React & Next.js",
    description: "Minta AI melakukan review kode React/Next.js dan menyarankan perbaikan.",
    category: "coding",
    content:
      "Bertindaklah sebagai senior React/Next.js engineer. Review kode berikut dan berikan: 1) bug atau potensi error, 2) masalah performa, 3) perbaikan best practice (hooks, TypeScript, aksesibilitas), 4) versi kode yang sudah diperbaiki dengan penjelasan. Kode:\n\n```\n[TEMPEL KODE]\n```",
    usage: "Tempel kode komponen atau file yang ingin direview.",
    exampleOutput: "Bug: useEffect tanpa dependency array menyebabkan...",
    level: "Lanjutan",
    supportedAi: ai.code,
    tags: ["react", "nextjs", "code review", "typescript"],
    followUps: [
      "Refactor kode yang sudah diperbaiki agar sepenuhnya mengikuti prinsip SOLID dan pisahkan logika ke custom hook bila memungkinkan.",
      "Tulis unit test lengkap (React Testing Library + Vitest) untuk komponen hasil perbaikan, termuk edge case dan error state.",
      "Analisis performa: identifikasi re-render yang tidak perlu, sarankan memoization, dan tunjukkan sebelum/sesudah dengan penjelasan.",
    ],
    isPremium: true,
    isTrending: true,
    isBestSeller: true,
    usersCount: 2980,
    copyCount: 5600,
  },
  {
    slug: "generate-api-nodejs-express",
    title: "Generate REST API Node.js Express",
    description: "Bangun struktur REST API lengkap dengan Express, validasi, dan error handling.",
    category: "coding",
    content:
      "Buatkan REST API menggunakan Node.js + Express untuk resource [ISI RESOURCE, mis. produk]. Sertakan: struktur folder, route CRUD lengkap, controller, validasi input, error handling middleware, dan contoh koneksi database. Gunakan TypeScript dan best practice. Jelaskan setiap file secara singkat.",
    usage: "Sebutkan resource dan kebutuhan spesifik API-mu.",
    exampleOutput: "Struktur: /src/routes, /src/controllers ...",
    level: "Lanjutan",
    supportedAi: ai.code,
    tags: ["nodejs", "express", "rest api", "backend"],
    isPremium: true,
    usersCount: 1760,
    copyCount: 2900,
  },
  {
    slug: "python-data-cleaning",
    title: "Python Data Cleaning Otomatis",
    description: "Skrip Python untuk membersihkan dan menyiapkan dataset dengan pandas.",
    category: "coding",
    content:
      "Sebagai data engineer, tuliskan skrip Python dengan pandas untuk membersihkan dataset dengan masalah berikut: [ISI MASALAH, mis. nilai kosong, duplikat, format tanggal]. Sertakan komentar penjelasan setiap langkah dan ringkasan sebelum/sesudah cleaning.",
    usage: "Deskripsikan kondisi dataset dan masalah yang ingin dibersihkan.",
    exampleOutput: "import pandas as pd\ndf = pd.read_csv(...) ...",
    level: "Menengah",
    supportedAi: ai.code,
    tags: ["python", "pandas", "data", "cleaning"],
    isPremium: false,
    usersCount: 1420,
    copyCount: 2100,
  },
  {
    slug: "landing-page-wireframe",
    title: "Wireframe Landing Page Konversi",
    description: "Rancang struktur wireframe landing page yang fokus konversi.",
    category: "ui-ux",
    content:
      "Bertindaklah sebagai UX designer. Rancang struktur wireframe landing page untuk [ISI PRODUK/JASA]. Uraikan section per section (hero, social proof, benefit, fitur, pricing, FAQ, CTA), tujuan tiap section, elemen yang harus ada, dan saran copy singkat. Sertakan prinsip konversi yang diterapkan.",
    usage: "Isi produk/jasa untuk mendapatkan blueprint landing page.",
    exampleOutput: "Hero — Tujuan: menangkap perhatian dalam 5 detik...",
    level: "Menengah",
    supportedAi: ai.chat,
    tags: ["landing page", "wireframe", "ux", "konversi"],
    isPremium: false,
    usersCount: 1680,
    copyCount: 2400,
  },
  {
    slug: "dashboard-ui-design-system",
    title: "Design System untuk Dashboard",
    description: "Panduan design system: warna, tipografi, komponen untuk dashboard SaaS.",
    category: "ui-ux",
    content:
      "Susun design system untuk aplikasi dashboard SaaS [ISI NAMA]. Sertakan palet warna (primary, secondary, semantic), skala tipografi, spacing scale, daftar komponen inti (button, input, card, table, modal) dengan state-nya, dan panduan aksesibilitas. Tampilkan dalam format terstruktur.",
    usage: "Sebutkan nama produk dan nuansa brand yang diinginkan.",
    exampleOutput: "Warna Primary: #6366f1 (Indigo) ...",
    level: "Lanjutan",
    supportedAi: ai.chat,
    tags: ["design system", "dashboard", "saas", "ui"],
    isPremium: true,
    usersCount: 980,
    copyCount: 1500,
  },
  {
    slug: "midjourney-produk-fotografi",
    title: "Midjourney Foto Produk Premium",
    description: "Prompt Midjourney untuk foto produk profesional dengan pencahayaan studio.",
    category: "desain",
    content:
      "professional product photography of [ISI PRODUK], studio lighting, soft shadows, minimalist background, high detail, commercial advertising style, 8k, sharp focus --ar 4:5 --style raw --v 6\n\nBuat juga 5 variasi dengan latar dan mood berbeda (mewah, natural, cerah, gelap dramatis, pastel).",
    usage: "Ganti [ISI PRODUK] dengan nama produkmu dan jalankan di Midjourney.",
    exampleOutput: "professional product photography of luxury serum bottle...",
    level: "Pemula",
    supportedAi: ai.image,
    tags: ["midjourney", "image prompt", "produk", "fotografi"],
    isPremium: true,
    isTrending: true,
    usersCount: 3400,
    copyCount: 6100,
  },
  {
    slug: "canva-konten-instagram-carousel",
    title: "Konsep Konten Carousel Instagram",
    description: "Ide dan struktur konten carousel Instagram yang edukatif dan engaging.",
    category: "desain",
    content:
      "Buatkan konsep konten carousel Instagram 8 slide tentang [ISI TOPIK] untuk audiens [ISI TARGET]. Untuk tiap slide berikan: headline, poin isi, dan saran visual/ikon. Slide pertama harus hook, slide terakhir CTA. Sertakan caption dan 15 hashtag relevan.",
    usage: "Isi topik dan target, lalu desain di Canva mengikuti struktur.",
    exampleOutput: "Slide 1 (Hook): \"5 Kesalahan yang Bikin...\"",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["canva", "instagram", "carousel", "konten"],
    isPremium: false,
    isBestSeller: true,
    usersCount: 4100,
    copyCount: 7200,
  },
  {
    slug: "email-profesional-bisnis",
    title: "Penulis Email Profesional",
    description: "Buat email bisnis profesional untuk berbagai keperluan dengan cepat.",
    category: "produktivitas",
    content:
      "Tuliskan email profesional untuk keperluan berikut: [ISI KEPERLUAN, mis. penawaran kerja sama]. Penerima: [ISI PENERIMA]. Tone: [formal/semi-formal]. Sertakan subjek yang menarik, pembuka, isi yang ringkas dan jelas, dan penutup dengan CTA. Berikan versi bahasa Indonesia dan Inggris.",
    usage: "Isi keperluan dan penerima untuk email siap kirim.",
    exampleOutput: "Subjek: Peluang Kerja Sama [Nama Perusahaan]...",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["email", "profesional", "bisnis", "produktivitas"],
    isPremium: false,
    usersCount: 5200,
    copyCount: 9800,
  },
  {
    slug: "cv-ats-friendly",
    title: "CV & Resume ATS-Friendly",
    description: "Susun CV yang lolos sistem ATS dan menonjolkan pencapaian.",
    category: "produktivitas",
    content:
      "Bertindaklah sebagai HR recruiter berpengalaman. Buatkan CV ATS-friendly untuk posisi [ISI POSISI] berdasarkan data berikut: [ISI PENGALAMAN & SKILL]. Fokus pada pencapaian terukur (angka), gunakan kata kerja aksi, dan susun ringkas 1 halaman. Sertakan ringkasan profil dan bagian skill relevan.",
    usage: "Masukkan pengalaman kerja dan skill-mu untuk hasil optimal.",
    exampleOutput: "Ringkasan Profil: Digital marketer dengan 3 tahun...",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["cv", "resume", "ats", "karier"],
    followUps: [
      "Berdasarkan CV di atas, tulis cover letter 1 halaman yang dipersonalisasi untuk lowongan berikut: [TEMPEL DESKRIPSI LOWONGAN].",
      "Optimalkan CV agar cocok dengan kata kunci ATS dari deskripsi lowongan ini: [TEMPEL DESKRIPSI], dan tandai kata kunci yang berhasil dimasukkan.",
      "Buat 10 pertanyaan interview yang mungkin ditanyakan berdasarkan CV ini, lengkap dengan contoh jawaban metode STAR.",
    ],
    isPremium: true,
    isTrending: true,
    usersCount: 3900,
    copyCount: 6900,
  },
  {
    slug: "notulen-meeting-otomatis",
    title: "Notulen Meeting Otomatis",
    description: "Ubah catatan meeting berantakan menjadi notulen rapi dengan action items.",
    category: "produktivitas",
    content:
      "Ringkas catatan meeting berikut menjadi notulen profesional: [TEMPEL CATATAN]. Format: judul meeting, tanggal, peserta, ringkasan pembahasan per topik, keputusan, dan tabel action items (tugas, PIC, deadline). Bahasa jelas dan ringkas.",
    usage: "Tempel catatan mentah dari meeting untuk mendapat notulen rapi.",
    exampleOutput: "Notulen Rapat Mingguan — Keputusan: ...",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["notulen", "meeting", "produktivitas", "ringkasan"],
    isPremium: false,
    usersCount: 2600,
    copyCount: 4300,
  },
  {
    slug: "essay-akademik-terstruktur",
    title: "Essay Akademik Terstruktur",
    description: "Kerangka dan draft essay akademik dengan argumen yang kuat.",
    category: "pendidikan",
    content:
      "Bertindaklah sebagai dosen pembimbing. Buatkan kerangka dan draft essay akademik tentang [ISI TOPIK] dengan sudut pandang [ISI SUDUT PANDANG]. Sertakan pendahuluan dengan thesis statement, 3 paragraf argumen dengan bukti, counter-argument, dan kesimpulan. Gunakan bahasa akademik dan sarankan referensi yang bisa dicari.",
    usage: "Isi topik dan sudut pandang; verifikasi referensi secara manual.",
    exampleOutput: "Pendahuluan: Dalam beberapa dekade terakhir...",
    level: "Menengah",
    supportedAi: ai.all,
    tags: ["essay", "akademik", "skripsi", "tulisan"],
    isPremium: false,
    usersCount: 3100,
    copyCount: 5200,
  },
  {
    slug: "ringkasan-materi-belajar",
    title: "Ringkasan Materi Belajar Cepat",
    description: "Ubah materi panjang menjadi ringkasan mudah dipahami dengan poin kunci.",
    category: "pendidikan",
    content:
      "Ringkas materi berikut menjadi catatan belajar yang mudah dipahami: [TEMPEL MATERI]. Sertakan: poin-poin kunci, definisi istilah penting, analogi sederhana, dan 5 soal latihan beserta jawaban untuk menguji pemahaman.",
    usage: "Tempel materi kuliah atau bab buku yang ingin diringkas.",
    exampleOutput: "Poin Kunci: 1) ... 2) ...",
    level: "Pemula",
    supportedAi: ai.chat,
    tags: ["ringkasan", "belajar", "mahasiswa", "catatan"],
    isPremium: false,
    isBestSeller: true,
    usersCount: 4400,
    copyCount: 7600,
  },
  {
    slug: "whatsapp-ai-auto-reply",
    title: "WhatsApp AI Auto-Reply Bisnis",
    description: "Desain alur auto-reply WhatsApp AI untuk menjawab pertanyaan pelanggan.",
    category: "ai-automation",
    content:
      "Rancang alur (flow) auto-reply WhatsApp berbasis AI untuk bisnis [ISI BISNIS]. Sertakan: menu utama, jawaban FAQ, alur pemesanan, eskalasi ke manusia, dan contoh prompt sistem untuk chatbot agar tetap ramah dan on-brand. Tampilkan sebagai diagram teks dan contoh percakapan.",
    usage: "Isi jenis bisnis untuk mendapatkan blueprint chatbot.",
    exampleOutput: "Menu Utama: 1) Katalog 2) Cek Pesanan 3) CS ...",
    level: "Lanjutan",
    supportedAi: ai.all,
    tags: ["whatsapp", "chatbot", "automation", "ai"],
    isPremium: true,
    isTrending: true,
    usersCount: 1900,
    copyCount: 3100,
  },
  {
    slug: "sales-ai-lead-scoring",
    title: "Sales AI Lead Scoring & Outreach",
    description: "Sistem scoring lead dan pesan outreach yang dipersonalisasi.",
    category: "ai-automation",
    content:
      "Bertindaklah sebagai sales ops. Buat sistem lead scoring sederhana (kriteria + bobot) untuk produk [ISI PRODUK], lalu tuliskan template pesan outreach yang dipersonalisasi untuk 3 kategori lead (dingin, hangat, panas). Sertakan follow-up cadence.",
    usage: "Isi produk dan profil pelanggan idealmu.",
    exampleOutput: "Kriteria: Ukuran perusahaan (bobot 30%)...",
    level: "Lanjutan",
    supportedAi: ai.all,
    tags: ["sales", "lead scoring", "crm", "outreach"],
    isPremium: true,
    usersCount: 1120,
    copyCount: 1800,
  },
  {
    slug: "chain-of-thought-reasoning",
    title: "Chain of Thought Reasoning",
    description: "Template prompt untuk memicu penalaran bertahap yang akurat.",
    category: "prompt-engineering",
    content:
      "Selesaikan masalah berikut dengan berpikir langkah demi langkah. Uraikan penalaranmu secara eksplisit sebelum memberi jawaban akhir. Jika ada asumsi, sebutkan. Verifikasi kembali hasilnya sebelum menyimpulkan.\n\nMasalah: [ISI MASALAH]\n\nFormat jawaban:\n1. Pemahaman masalah\n2. Langkah penyelesaian\n3. Verifikasi\n4. Jawaban akhir",
    usage: "Gunakan untuk soal logika, matematika, atau analisis kompleks.",
    exampleOutput: "1. Pemahaman masalah: ...",
    level: "Menengah",
    supportedAi: ai.all,
    tags: ["chain of thought", "reasoning", "prompt engineering"],
    isPremium: false,
    isBestSeller: true,
    usersCount: 2800,
    copyCount: 4900,
  },
  {
    slug: "role-prompt-expert-persona",
    title: "Role Prompt Expert Persona",
    description: "Bangun persona ahli yang detail agar jawaban AI lebih tajam.",
    category: "prompt-engineering",
    content:
      "Kamu adalah [ISI PERAN, mis. ahli strategi keuangan] dengan pengalaman 15 tahun di [ISI BIDANG]. Gaya komunikasimu: [tegas/edukatif/ringkas]. Batasan: hanya menjawab dalam lingkup keahlianmu, akui bila tidak yakin. Tugasmu: [ISI TUGAS]. Ajukan pertanyaan klarifikasi bila informasi kurang sebelum menjawab.",
    usage: "Definisikan peran, bidang, dan tugas untuk output yang lebih relevan.",
    exampleOutput: "Baik. Sebelum menjawab, saya perlu tahu...",
    level: "Menengah",
    supportedAi: ai.all,
    tags: ["role prompt", "persona", "prompt engineering"],
    isPremium: true,
    isTrending: true,
    usersCount: 2300,
    copyCount: 4200,
  },
  {
    slug: "few-shot-klasifikasi",
    title: "Few-Shot Klasifikasi Teks",
    description: "Template few-shot untuk klasifikasi teks yang konsisten.",
    category: "prompt-engineering",
    content:
      "Klasifikasikan teks ke dalam kategori: [ISI KATEGORI]. Ikuti contoh berikut:\n\nTeks: \"contoh 1\" -> Kategori: A\nTeks: \"contoh 2\" -> Kategori: B\nTeks: \"contoh 3\" -> Kategori: A\n\nSekarang klasifikasikan:\nTeks: \"[ISI TEKS]\" -> Kategori:",
    usage: "Isi kategori dan contoh untuk hasil klasifikasi konsisten.",
    exampleOutput: "Teks: \"pengiriman lambat\" -> Kategori: Komplain",
    level: "Lanjutan",
    supportedAi: ai.all,
    tags: ["few shot", "klasifikasi", "prompt engineering"],
    isPremium: true,
    usersCount: 890,
    copyCount: 1300,
  },
];

export const plansSeed = [
  {
    slug: "free",
    name: "Gratis 7 Hari",
    price: 0,
    period: "7 hari",
    highlighted: false,
    sortOrder: 1,
    features: ["70 Prompt pilihan", "Copy 1x per prompt", "Akses 7 hari per perangkat", "Update terbatas"],
  },
  {
    slug: "pro",
    name: "Pro",
    price: 899000,
    period: "sekali bayar",
    highlighted: true,
    sortOrder: 2,
    features: [
      "Akses selamanya ke 1000+ prompt premium",
      "Copy tanpa batas",
      "Prompt Troubleshooter",
      "Update selamanya",
      "AI Workflow & Automation",
      "Support prioritas",
    ],
  },
  {
    slug: "enterprise",
    name: "Enterprise",
    price: 0,
    period: "custom",
    highlighted: false,
    sortOrder: 3,
    features: [
      "Lisensi tim & perusahaan",
      "Prompt kustom on-demand",
      "SOP & workflow internal",
      "Onboarding & pelatihan",
      "Dedicated support",
    ],
  },
];

export const reviewsSeed = [
  { promptSlug: "meta-ads-skincare-konversi-tinggi", author: "Rina S.", rating: 5, comment: "CTR iklan naik 2x lipat setelah pakai ini. Recommended!", likes: 42 },
  { promptSlug: "meta-ads-skincare-konversi-tinggi", author: "Bagus P.", rating: 4, comment: "Copy-nya persuasif, tinggal sedikit edit.", likes: 12 },
  { promptSlug: "review-kode-react-nextjs", author: "Dimas F.", rating: 5, comment: "Nemu bug yang kelewat selama seminggu. Mantap.", likes: 30 },
  { promptSlug: "cv-ats-friendly", author: "Sari L.", rating: 5, comment: "Langsung dipanggil interview. Terima kasih!", likes: 55 },
  { promptSlug: "midjourney-produk-fotografi", author: "Andi K.", rating: 5, comment: "Hasil foto produknya premium banget.", likes: 28 },
];
